export const usersMock = [
  {
    id: 1,
    firstName: 'Alice',
    lastName: 'Smith',
    email: 'alice.smith@example.com',
    login: 'alice123',
    password: 'qwerty',
    active: true,
  },
  {
    id: 2,
    firstName: 'Bob',
    lastName: 'Jones',
    email: 'bob.jones@example.com',
    login: 'bob456',
    password: 'password',
    active: true,
  },
  {
    id: 3,
    firstName: 'Charlie',
    lastName: 'Brown',
    email: 'charlie.brown@example.com',
    login: 'charlie789',
    password: 'letmein',
    active: false,
  },
  {
    id: 4,
    firstName: 'David',
    lastName: 'Lee',
    email: 'david.lee@example.com',
    login: 'davidL',
    password: '123456',
    active: true,
  },
  {
    id: 5,
    firstName: 'Emily',
    lastName: 'Davis',
    email: 'emily.davis@example.com',
    login: 'emilyD',
    password: 'abcd',
    active: false,
  },
  {
    id: 6,
    firstName: 'Frank',
    lastName: 'Kim',
    email: 'frank.kim@example.com',
    login: 'frank123',
    password: 'password123',
    active: true,
  },
  {
    id: 7,
    firstName: 'Grace',
    lastName: 'Wang',
    email: 'grace.wang@example.com',
    login: 'graceW',
    password: 'qwertyuiop',
    active: true,
  },
  {
    id: 8,
    firstName: 'Henry',
    lastName: 'Chen',
    email: 'henry.chen@example.com',
    login: 'henryC',
    password: 'asdfghjkl',
    active: false,
  },
  {
    id: 9,
    firstName: 'Isabella',
    lastName: 'Nguyen',
    email: 'isabella.nguyen@example.com',
    login: 'isabellaN',
    password: 'zxcvbnm',
    active: true,
  },
  {
    id: 10,
    firstName: 'Jack',
    lastName: 'Garcia',
    email: 'jack.garcia@example.com',
    login: 'jackG',
    password: 'letmein123',
    active: false,
  },
];
